Add 'Meet Capact maintainers (..)' blog post
capactio/website pull request #88
Opened 2021-12-13 16:00 UTC by mszostok

## Description

Changes proposed in this pull request:

- Add **'Meet Capact maintainers and learn how to become one!'** blog post

2021-12-14 10:33 UTC, mkuziemko approved these changes
I read carefully and I didn't spot mistakes. Very good work! :1st_place_medal:

2021-12-15 13:01 UTC, tmitchell requested changes
I personally enjoyed reading this to get to hear more of your backstory!

2021-12-15 19:17 UTC, sunny-dasgupta-braingu requested changes

2021-12-15 19:17 UTC, sunny-dasgupta-braingu commented on blog/2021-12-13-maintainers-interview.md
> +In the previous blog post, you learned which problems Capact aims to solve. This time, Capact maintainers took some time to answer questions you might have if you're considering contributing to the p
In a previous blog post, we discussed some of the problems Capact aims to solve. This time, Capact maintainers took some time to answer questions you might have if you're considering contributing to the project.

2021-12-15 19:17 UTC, sunny-dasgupta-braingu commented on blog/2021-12-13-maintainers-interview.md
> +My journey with IT actually started thanks to my brother. The first program that I wrote was on Commodore 64 when I was about 10 years old. Since then, I have been involved in technology. From the be
Agreed. If you're going to mention your brother, a quick one sentence on how your brother got you started would be good.

2021-12-15 19:17 UTC, sunny-dasgupta-braingu commented on blog/2021-12-13-maintainers-interview.md
> +**Paweł:** Capact is an open-source framework for running arbitrary workflows. Initially, we are focused on day-one and day-two workflows for deploying, and managing applications and cloud-native inf
Capact is an open-source framework for running arbitrary workflows. Currently, we are focusing on day-one and day-two workflows for deploying, and managing applications and cloud-native infrastructure.

2021-12-17 14:38 UTC, pkosiec commented on blog/2021-12-13-maintainers-interview.md
> +**Paweł:** Capact consists of many technologies, and you can learn a lot. Even if you know some of them, while working on Capact, you will have an opportunity to dive deeply into some stuff you have
That's good idea, we will do it 👍

2021-12-23 16:58 UTC, tmitchell approved these changes

2021-12-23 23:01 UTC, merged